const SENDGRID_API_KEY = "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";
const SENDGRID_AUTH_KEY = "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"

export { SENDGRID_API_KEY, SENDGRID_AUTH_KEY };